### ISSUE TITLE
cannot create programs 

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/ecodata#6]
2020-09-23 14:45:59,722 [https-openssl-apr-443-exec-140] ERROR errors.GrailsExceptionResolver  - MissingMethodException occurred when processing request: [POST] /admin/updateProgramsModel
No signature of method: groovy.util.ConfigObject.plus() is applicable for argument types: (java.lang.String) values: []
Possible solutions: plus(java.util.Map), plus(java.util.Collection), values(), put(java.lang.Object, java.lang.Object), split(groovy.lang.Closure), minus(java.util.Map). Stacktrace follows:
groovy.lang.MissingMethodException: No signature of method: groovy.util.ConfigObject.plus() is applicable for argument types: (java.lang.String) values: []
Possible solutions: plus(java.util.Map), plus(java.util.Collection), values(), put(java.lang.Object, java.lang.Object), split(groovy.lang.Closure), minus(java.util.Map)
    at au.org.ala.ecodata.MetadataService.writeWithBackup(MetadataService.groovy:231)
    at au.org.ala.ecodata.MetadataService.updateProgramsModel(MetadataService.groovy:255)
    at au.org.ala.ecodata.AdminController.updateProgramsModel(AdminController.groovy:568)
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at au.org.ala.cas.client.AlaHttpServletRequestWrapperFilter.doFilter(AlaHttpServletRequestWrapperFilter.java:66)
    at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:189)
    at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:196)
    at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:189)
    at org.jasig.cas.client.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:93)
    at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:189)
    at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by magdziarek** [comment]
adding in config.groovy path for models solved it: 
  production {
+      app.external.model.dir = "/data/ecodata/models/"
         grails.logging.jul.usebridge = false
         app.elasticsearch.indexAllOnStartup = false // Makes deployments too slow
